import "./globals.css";
import Header from "@/components/Header";
import Chats from "@/components/Chats";


export const metadata = {
  title: "Sawa Space",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Chats/>
        <main>
          <Header/>
          {children}
        </main>
      </body>
    </html>
  );
}
