import { FaLaptopCode, FaBasketballBall, FaHeart, FaCar } from "react-icons/fa";

import { MdLocalGroceryStore, MdOutlinePets } from "react-icons/md";
import {
  IoHome,
  IoPhonePortrait,
  IoHardwareChip,
  IoGameController,
} from "react-icons/io5";
import { TbTools, TbDeviceGamepad3Filled } from "react-icons/tb";
import { GiRolledCloth } from "react-icons/gi";
import { CgGirl } from "react-icons/cg";

export const departements = [
  { name: "home related", icon: IoHome },
  { name: "phones", icon: IoPhonePortrait },
  { name: "hardware", icon: IoHardwareChip },
  { name: "accessories", icon: TbTools },
  { name: "computers", icon: FaLaptopCode },
  { name: "consoles", icon: TbDeviceGamepad3Filled },
  { name: "toys and games", icon: IoGameController },
  { name: "sports equipment", icon: FaBasketballBall },
  { name: "fashion", icon: GiRolledCloth },
  { name: "health", icon: FaHeart },
  { name: "beauty", icon: CgGirl },
  { name: "vehicles", icon: FaCar },
  { name: "pet supplies", icon: MdOutlinePets },
  { name: "grocery", icon: MdLocalGroceryStore },
];

export const users = [
  {
    id: 1,
    name: "Ahmed mouhamed",
    img: "/users/user1.png",
    lastMessage: {
      type: "text",
      content:
        "Hey there iam her papy ooohh yaaaa! shadow fight no way stop fk",
    },
    bio: "Tech enthusiast",
    number: "+20 112 972 7995",
    lastMsgTime: "2025-03-03T09:40:00Z",
    isGroup: false,
    unReadCounter: 2,
    groupMembers: [],
    newStatus: false,
  },
  {
    id: 2,
    name: "Sara",
    img: "/users/user2.png",
    lastMessage: { type: "img" },
    bio: "Photographer",
    number: "+20 112 972 7995",

    lastMsgTime: "2025-03-14T09:40:00Z",
    isGroup: false,
    unReadCounter: 13,
    groupMembers: [],
    newStatus: true,
  },
  {
    id: 3,
    name: "Football Fans",
    img: "/users/user3.png",
    number: "+20 112 972 7995",

    lastMessage: { type: "sticker", content: "⚽" },
    bio: "Group of football lovers",
    lastMsgTime: "2025-03-08T09:40:00Z",
    isGroup: true,
    unReadCounter: 0,
    groupMembers: ["Ali", "Hassan", "Omar"],
    newStatus: false,
  },
  {
    id: 4,
    name: "Ali",
    img: "/users/user4.png",
    lastMessage: { type: "text", content: "How was your day?" },
    bio: "Gamer",
    lastMsgTime: "2025-02-25T09:40:00Z",
    isGroup: false,
    number: "+20 112 972 7995",

    unReadCounter: 1,
    groupMembers: [],
    newStatus: false,
  },
  {
    id: 5,
    name: "Family Chat",
    img: "/users/user5.png",
    lastMessage: { type: "text", content: "Dinner plans?" },
    bio: "Family chat group",
    lastMsgTime: "2025-02-01T09:40:00Z",
    isGroup: true,
    unReadCounter: 0,
    number: "+20 112 972 7995",

    groupMembers: ["Dad", "Mom", "Sister"],
    newStatus: false,
  },
  {
    id: 6,
    name: "Omar",
    img: "/users/user6.png",
    lastMessage: { type: "sticker", content: "🎉" },
    bio: "Musician",
    lastMsgTime: "2024-03-03T09:40:00Z",
    isGroup: false,
    number: "+20 112 972 7995",

    unReadCounter: 8,
    groupMembers: [],
    newStatus: true,
  },
  {
    id: 7,
    name: "Study Crew",
    img: "/users/user7.png",
    lastMessage: { type: "img" },
    bio: "Group for study discussions",
    lastMsgTime: "2023-03-03T09:40:00Z",
    number: "+20 112 972 7995",

    isGroup: true,
    unReadCounter: 2,
    groupMembers: ["John", "Sara", "Mike"],
    newStatus: false,
  },
  {
    id: 8,
    name: "Nour",
    img: "/users/user8.png",
    lastMessage: { type: "text", content: "Call me later." },
    bio: "Traveler",
    number: "+20 112 972 7995",

    lastMsgTime: "2022-03-03T09:40:00Z",
    isGroup: false,
    unReadCounter: 0,
    groupMembers: [],
    newStatus: true,
  },
  {
    id: 9,
    name: "Gaming Legends",
    img: "/users/user9.png",
    lastMessage: { type: "sticker", content: "🎮" },
    bio: "Gaming chat",
    lastMsgTime: "2025-03-01T09:40:00Z",
    isGroup: true,
    unReadCounter: 0,
    number: "+20 112 972 7995",

    groupMembers: ["Ali", "Ahmed", "Sara"],
    newStatus: false,
  },
  {
    id: 10,
    name: "Hassan",
    img: "/users/user10.png",
    lastMessage: { type: "img" },
    bio: "Coder",
    number: "+20 112 972 7995",

    lastMsgTime: "2025-03-15T09:39:00Z",
    isGroup: false,
    unReadCounter: 2,
    groupMembers: [],
    newStatus: false,
  },
  {
    id: 11,
    name: "Music Lovers",
    img: "/users/user11.png",
    lastMessage: { type: "text", content: "Check out this song!" },
    bio: "For music sharing",
    lastMsgTime: "2025-03-15T09:38:00Z",
    isGroup: true,
    number: "+20 112 972 7995",

    unReadCounter: 0,
    groupMembers: ["Ahmed", "Omar", "Nour"],
    newStatus: false,
  },
  {
    id: 12,
    name: "Mike",
    img: "/users/user12.png",
    lastMessage: { type: "sticker", content: "🤓" },
    bio: "Developer",
    lastMsgTime: "2025-03-15T08:40:00Z",
    isGroup: false,
    number: "+20 112 972 7995",

    unReadCounter: 0,
    groupMembers: [],
    newStatus: false,
  },
  {
    id: 13,
    name: "Book Circle",
    img: "/users/user13.png",
    lastMessage: { type: "img" },
    bio: "Book enthusiasts",
    number: "+20 112 972 7995",

    lastMsgTime: "2025-03-15T07:40:00Z",
    isGroup: true,
    unReadCounter: 0,
    groupMembers: ["Sara", "John", "Ali"],
    newStatus: true,
  },
  {
    id: 14,
    name: "John",
    img: "/users/user14.png",
    lastMessage: { type: "text", content: "Meeting at 5?" },
    bio: "Entrepreneur",
    lastMsgTime: "2025-03-15T00:40:00Z",
    isGroup: false,
    unReadCounter: 0,
    number: "+20 112 972 7995",

    groupMembers: [],
    newStatus: false,
  },
  {
    id: 15,
    name: "Tech World",
    img: "/users/user15.png",
    lastMessage: { type: "text", content: "New iPhone launched!" },
    bio: "Latest technology updates",
    lastMsgTime: "2025-03-14T23:59:00Z",
    number: "+20 112 972 7995",

    isGroup: true,
    unReadCounter: 0,
    groupMembers: ["Ahmed", "Nour", "Sara"],
    newStatus: true,
  },
];

export let messages = [
  {
    id: 1,
    user: "Alice",
    message: "",
    img: "/chat3.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:00",
    pin: true,
  },
  {
    id: 2,
    user: "Bob",
    message: "I'm good, thanks! How about you?",
    img: null,
    replyId: 1,
    date: "2024-10-12",
    time: "16:05",
  },
  {
    id: 3,
    user: "Alice",
    message: "Doing well, just working on a project.",
    img: "/chat4.png",
    replyId: 12,
    date: "2024-10-12",
    time: "16:10",
  },
  {
    id: 6684,
    actor: "endy",
    action: "join the group using via link",
  },
  {
    id: 4,
    user: "Bob",
    message: "That's great! What's the project about?",
    img: null,
    replyId: 3,
    date: "2024-10-12",
    time: "16:15",
    deleted: true,
  },
  {
    id: 5,
    user: "Alice",
    message: "It's a web app for managing tasks. What about you?",
    img: "/chat6.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:20",
    pin: true,
  },
  {
    id: 616,
    history: true,
    time: "1/14/2025",
  },
  {
    id: 626,
    actor: "endy",
    action: "added",
    targetPerson: "3kr4",
  },

  {
    id: 6476,
    actor: "ixon",
    action: "left",
  },

  {
    id: 6160,
    actor: "endy",
    action: "giveAadmin",
    targetPerson: "3kr4",
  },

  {
    id: 6,
    user: "Bob",
    message: "Just learning new things in React.",
    img: null,
    replyId: null,
    date: "2024-10-12",
    time: "16:25",
  },
  {
    id: 7,
    user: "Alice",
    message: "React is amazing! Have you tried Next.js?",
    img: null,
    replyId: 6,
    date: "2024-10-12",
    time: "16:30",
    emojis: [
      {
        id: 1,
        user: {
          name: "Alias",
          img: "/users/user1.png",
        },
        emoji: "🧐",
      },
      {
        id: 2,
        user: {
          name: "Bob",
          img: "/users/user2.png",
        },
        emoji: "🤓",
      },
      {
        id: 3,
        user: {
          name: "sass",
          img: "/users/user4.png",
        },
        emoji: "😭",
      },
      {
        id: 4,
        user: {
          name: "Alias",
          img: "/users/user6.png",
        },
        emoji: "🧐",
      },
      {
        id: 5,
        user: {
          name: "Bob",
          img: "/users/user7.png",
        },
        emoji: "🤓",
      },
      {
        id: 6,
        user: {
          name: "sass",
          img: "/users/user8.png",
        },
        emoji: "😭",
      },
      {
        id: 7,
        user: {
          name: "Alias",
          img: "/users/user10.png",
        },
        emoji: "🧐",
      },
      {
        id: 8,
        user: {
          name: "Bob",
          img: "/users/user12.png",
        },
        emoji: "🤓",
      },
      {
        id: 9,
        user: {
          name: "sass",
          img: "/users/user15.png",
        },
        emoji: "😭",
      },
      {
        id: 10,
        user: {
          name: "Alias",
          img: "/users/user1.png",
        },
        emoji: "🤩",
      },
      {
        id: 11,
        user: {
          name: "Bob",
          img: "/users/user2.png",
        },
        emoji: "🥶",
      },
      {
        id: 12,
        user: {
          name: "sass",
          img: "/users/user4.png",
        },
        emoji: "🤮",
      },
    ],
  },
  {
    id: 8,
    user: "Bob",
    message: "Not yet, but it's on my list. Do you use it?",
    img: "/chat1.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:35",
    emojis: [
      {
        id: 1,
        user: {
          name: "Alias",
          img: "/users/user2.png",
        },
        emoji: "🥰",
      },
      {
        id: 2,
        user: {
          name: "Bob",
          img: "/users/user8.png",
        },
        emoji: "👎🏻",
      },
      {
        id: 3,
        user: {
          name: "sass",
          img: "/users/user7.png",
        },
        emoji: "😂",
      },
      {
        id: 2,
        user: {
          name: "Bob",
          img: "/users/user10.png",
        },
        emoji: "👎🏻",
      },
      {
        id: 3,
        user: {
          name: "sass",
          img: "/users/user12.png",
        },
        emoji: "😂",
      },
    ],
  },
  {
    id: 9,
    user: "Alice",
    message: "Yes, I use it for most of my projects. It's really powerful!",
    img: "/chat2.png",
    replyId: 8,
    date: "2024-10-12",
    time: "16:40",
  },
  {
    id: 10,
    user: "Bob",
    message: "Yes, I use it for most of my projects. It's really powerful!",
    img: null,
    replyId: null,
    date: "2024-10-12",
    time: "16:45",
  },

  {
    id: 11,
    user: "Alice",
    message: "",
    img: "/chat3.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:00",
  },
  {
    id: 12,
    user: "Bob",
    message: "I'm good, thanks! How about you?",
    img: null,
    replyId: 4,
    date: "2024-10-12",
    time: "16:05",
  },
  {
    id: 13,
    user: "Alice",
    message: "Doing well, just working on a project.",
    img: "/chat4.png",
    replyId: 2,
    date: "2024-10-12",
    time: "16:10",
  },
  {
    id: 14,
    user: "Bob",
    message: "That's great! What's the project about?",
    img: null,
    replyId: 3,
    date: "2024-10-12",
    time: "16:15",
    deleted: true,
  },
  {
    id: 61416,
    history: true,
    time: "Today",
  },

  {
    id: 15,
    user: "Alice",
    message: "It's a web app for managing tasks. What about you?",
    img: "/chat5.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:20",
  },
  {
    id: 16,
    user: "Bob",
    message: "Just learning new things in React.",
    img: null,
    replyId: null,
    date: "2024-10-12",
    time: "16:25",
  },
  {
    id: 615,
    actor: "3kr4",
    action: "remove",
    targetPerson: "fares",
  },

  {
    id: 17,
    user: "Alice",
    message: "React is amazing! Have you tried Next.js?",
    img: null,
    replyId: 6,
    date: "2024-10-12",
    time: "16:30",
  },
  {
    id: 18,
    user: "Bob",
    message: "Not yet, but it's on my list. Do you use it?",
    img: "/chat1.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:35",
    emojis: [
      {
        id: 1,
        user: {
          name: "Alias",
          img: "/users/user1.png",
        },
        emoji: "🥰",
      },
      {
        id: 2,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "👎🏻",
      },
      {
        id: 3,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "😂",
      },
      {
        id: 2,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "👎🏻",
      },
      {
        id: 3,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "😂",
      },
    ],
  },
  {
    id: 19,
    user: "Alice",
    message: "Yes, I use it for most of my projects. It's really powerful!",
    img: "/chat2.png",
    replyId: 8,
    date: "2024-10-12",
    time: "16:40",
  },
  {
    id: 20,
    user: "Bob",
    message: "Yes, I use it for most of my projects. It's really powerful!",
    img: null,
    replyId: null,
    date: "2024-10-12",
    time: "16:45",
  },

  {
    id: 21,
    user: "Alice",
    message: "",
    img: "/chat18.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:00",
  },
  {
    id: 22,
    user: "Bob",
    message: "I'm good, thanks! How about you?",
    img: null,
    replyId: 14,
    date: "2024-10-12",
    time: "16:05",
  },
  {
    id: 6116,
    history: true,
    time: "tharathday",
  },

  {
    id: 23,
    user: "Alice",
    message: "Doing well, just working on a project.",
    img: "/chat17.png",
    replyId: 2,
    date: "2024-10-12",
    time: "16:10",
  },
  {
    id: 24,
    user: "Bob",
    message: "That's great! What's the project about?",
    img: null,
    replyId: 3,
    date: "2024-10-12",
    time: "16:15",
    deleted: true,
  },
  {
    id: 69,
    actor: "3kr4",
    action: "removeAdmin",
    targetPerson: "endy",
  },
  {
    id: 25,
    user: "Alice",
    message: "It's a web app for managing tasks. What about you?",
    img: "/chat5.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:20",
  },
  {
    id: 26,
    user: "Bob",
    message: "Just learning new things in React.",
    img: null,
    replyId: null,
    date: "2024-10-12",
    time: "16:25",
  },
  {
    id: 27,
    user: "Alice",
    message: "React is amazing! Have you tried Next.js?",
    img: null,
    replyId: 6,
    date: "2024-10-12",
    time: "16:30",
    emojis: [
      {
        id: 1,
        user: {
          name: "Alias",
          img: "/users/user1.png",
        },
        emoji: "🧐",
      },
      {
        id: 2,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "🤓",
      },
      {
        id: 3,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "😭",
      },
      {
        id: 4,
        user: {
          name: "Alias",
          img: "/users/user1.png",
        },
        emoji: "🧐",
      },
      {
        id: 5,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "🤓",
      },
      {
        id: 6,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "😭",
      },
      {
        id: 7,
        user: {
          name: "Alias",
          img: "/users/user1.png",
        },
        emoji: "🧐",
      },
      {
        id: 8,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "🤓",
      },
      {
        id: 9,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "😭",
      },
      {
        id: 10,
        user: {
          name: "Alias",
          img: "/users/user1.png",
        },
        emoji: "🤩",
      },
      {
        id: 11,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "🥶",
      },
      {
        id: 12,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "🤮",
      },
    ],
  },
  {
    id: 28,
    user: "Bob",
    message: "Not yet, but it's on my list. Do you use it?",
    img: "/chat13.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:35",
    pin: false,
    emojis: [
      {
        id: 1,
        user: {
          name: "Alias",
          img: "/users/user1.png",
        },
        emoji: "🥰",
      },
      {
        id: 2,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "👎🏻",
      },
      {
        id: 3,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "😂",
      },
      {
        id: 2,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "👎🏻",
      },
      {
        id: 3,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "😂",
      },
    ],
  },
  {
    id: 29,
    user: "Alice",
    message: "Yes, I use it for most of my projects. It's really powerful!",
    img: "/chat15.png",
    replyId: 18,
    date: "2024-10-12",
    time: "16:40",
  },
  {
    id: 6136,
    history: true,
    time: "1/14/2026",
  },
  {
    id: 30,
    user: "Bob",
    message: "Yes, I use it for most of my projects. It's really powerful!",
    img: null,
    replyId: null,
    date: "2024-10-12",
    time: "16:45",
  },

  {
    id: 31,
    user: "Alice",
    message: "",
    img: "/chat6.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:00",
  },
  {
    id: 32,
    user: "Bob",
    message: "I'm good, thanks! How about you?",
    img: null,
    replyId: 19,
    date: "2024-10-12",
    time: "16:05",
  },
  {
    id: 33,
    user: "Alice",
    message: "Doing well, just working on a project.",
    img: "/chat7.png",
    replyId: 22,
    date: "2024-10-12",
    time: "16:10",
  },
  {
    id: 34,
    user: "Bob",
    message: "That's great! What's the project about?",
    img: null,
    replyId: 3,
    date: "2024-10-12",
    time: "16:15",
    deleted: true,
  },
  {
    id: 35,
    user: "Alice",
    message: "It's a web app for managing tasks. What about you?",
    img: "/chat8.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:20",
  },
  {
    id: 36,
    user: "Bob",
    message: "Just learning new things in React.",
    img: null,
    replyId: null,
    date: "2024-10-12",
    time: "16:25",
  },
  {
    id: 37,
    user: "Alice",
    message: "React is amazing! Have you tried Next.js?",
    img: null,
    replyId: 6,
    date: "2024-10-12",
    time: "16:30",
  },
  {
    id: 39,
    user: "Alice",
    message: "Yes, I use it for most of my projects. It's really powerful!",
    img: "/chat9.ico",
    replyId: 13,
    date: "2024-10-12",
    time: "16:40",
  },
  {
    id: 40,
    user: "Bob",
    message: "Yes, I use it for most of my projects. It's really powerful!",
    img: null,
    replyId: null,
    date: "2024-10-12",
    time: "16:45",
  },

  {
    id: 41,
    user: "Alice",
    message: "",
    img: "/chat10.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:00",
    pin: true,
  },
  {
    id: 42,
    user: "Bob",
    message: "I'm good, thanks! How about you?",
    img: null,
    replyId: 1,
    date: "2024-10-12",
    time: "16:05",
  },
  {
    id: 43,
    user: "Alice",
    message: "Doing well, just working on a project.",
    img: "/chat11.png",
    replyId: 23,
    date: "2024-10-12",
    time: "16:10",
  },
  {
    id: 44,
    user: "Bob",
    message: "That's great! What's the project about?",
    img: null,
    replyId: 3,
    date: "2024-10-12",
    time: "16:15",
    deleted: true,
  },
  {
    id: 45,
    user: "Alice",
    message: "It's a web app for managing tasks. What about you?",
    img: "/chat12.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:20",
  },
  {
    id: 46,
    user: "Bob",
    message: "Just learning new things in React.",
    img: null,
    replyId: null,
    date: "2024-10-12",
    time: "16:25",
  },
  {
    id: 47,
    user: "Alice",
    message: "React is amazing! Have you tried Next.js?",
    img: null,
    replyId: 6,
    date: "2024-10-12",
    time: "16:30",
    emojis: [
      {
        id: 1,
        user: {
          name: "Alias",
          img: "/users/user1.png",
        },
        emoji: "🧐",
      },
      {
        id: 2,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "🤓",
      },
      {
        id: 3,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "😭",
      },
      {
        id: 4,
        user: {
          name: "Alias",
          img: "/users/user1.png",
        },
        emoji: "🧐",
      },
      {
        id: 5,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "🤓",
      },
      {
        id: 6,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "😭",
      },
      {
        id: 7,
        user: {
          name: "Alias",
          img: "/users/user1.png",
        },
        emoji: "🧐",
      },
      {
        id: 8,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "🤓",
      },
      {
        id: 9,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "😭",
      },
      {
        id: 10,
        user: {
          name: "Alias",
          img: "/users/user1.png",
        },
        emoji: "🤩",
      },
      {
        id: 11,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "🥶",
      },
      {
        id: 12,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "🤮",
      },
    ],
  },
  {
    id: 48,
    user: "Bob",
    message: "Not yet, but it's on my list. Do you use it?",
    img: "/chat13.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:35",
    emojis: [
      {
        id: 1,
        user: {
          name: "Alias",
          img: "/users/user1.png",
        },
        emoji: "🥰",
      },
      {
        id: 2,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "👎🏻",
      },
      {
        id: 3,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "😂",
      },
      {
        id: 2,
        user: {
          name: "Bob",
          img: "/users/user1.png",
        },
        emoji: "👎🏻",
      },
      {
        id: 3,
        user: {
          name: "sass",
          img: "/users/user1.png",
        },
        emoji: "😂",
      },
    ],
  },
  {
    id: 49,
    user: "Alice",
    message: "Yes, I use it for most of my projects. It's really powerful!",
    img: "/chat19.png",
    replyId: 8,
    date: "2024-10-12",
    time: "16:40",
  },
  {
    id: 50,
    user: "Bob",
    message: "Yes, I use it for most of my projects. It's really powerful!",
    img: null,
    replyId: null,
    date: "2024-10-12",
    time: "16:45",
  },
];

export const user_orders = [
  {
    id: 1,
    from: "Rolex Submariner",
    orders: [
      {
        id: 1,
        products: [
          { id: 1, quantaty: 1 },
          { id: 2, quantaty: 3 },
          { id: 3, quantaty: 2 },
        ],
        drivery_location: "12 nasr city",
        date: "",
        total_price: 8000,
      },
      {
        id: 1,
        products: [
          { id: 1, quantaty: 1 },
          { id: 2, quantaty: 3 },
          { id: 3, quantaty: 2 },
        ],
        drivery_location: "12 nasr city",
        date: "",
        total_price: 2000,
      },
    ],
  },
  {
    id: 1,
    from: "Rolex Submariner",
    orders: [
      {
        id: 1,
        products: [
          { id: 1, quantaty: 1 },
          { id: 2, quantaty: 3 },
          { id: 3, quantaty: 2 },
        ],
        drivery_location: "12 nasr city",
        date: "",
        total_price: 1000,
      },
    ],
  },
  {
    id: 1,
    from: "Rolex Submariner",
    orders: [
      {
        id: 1,
        products: [
          { id: 1, quantaty: 1 },
          { id: 2, quantaty: 3 },
          { id: 3, quantaty: 2 },
        ],
        drivery_location: "12 nasr city",
        date: "",
        total_price: 1500,
      },
      {
        id: 1,
        products: [
          { id: 1, quantaty: 1 },
          { id: 2, quantaty: 3 },
          { id: 3, quantaty: 2 },
        ],
        drivery_location: "12 nasr city",
        date: "",
        total_price: 500,
      },
      {
        id: 1,
        products: [
          { id: 1, quantaty: 1 },
          { id: 2, quantaty: 3 },
          { id: 3, quantaty: 2 },
        ],
        drivery_location: "12 nasr city",
        date: "",
        total_price: 800,
      },
    ],
  },
];
