export let messages = [
  {
    id: 1,
    user: "Alice",
    message: "",
    img: "/chat3.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:00", 
  },
  {
    id: 2,
    user: "Bob",
    message: "I'm good, thanks! How about you?",
    img: "",
    replyId: 1,
    date: "2024-10-12",
    time: "16:05", 
  },
  {
    id: 3,
    user: "Alice",
    message: "Doing well, just working on a project.",
    img: "/chat4.png",
    replyId: 2,
    date: "2024-10-12",
    time: "16:10", 
  },
  {
    id: 4,
    user: "Bob",
    message: "That's great! What's the project about?",
    img: "",
    replyId: 3,
    date: "2024-10-12",
    time: "16:15", 
  },
  {
    id: 5,
    user: "Alice",
    message: "It's a web app for managing tasks. What about you?",
    img: "/chat5.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:20", 
  },
  {
    id: 6,
    user: "Bob",
    message: "Just learning new things in React.",
    img: "",
    replyId: null,
    date: "2024-10-12",
    time: "16:25", 
  },
  {
    id: 7,
    user: "Alice",
    message: "React is amazing! Have you tried Next.js?",
    img: "",
    replyId: 6,
    date: "2024-10-12",
    time: "16:30", 
  },
  {
    id: 8,
    user: "Bob",
    message: "Not yet, but it's on my list. Do you use it?",
    img: "/chat1.png",
    replyId: null,
    date: "2024-10-12",
    time: "16:35", 
  },
  {
    id: 9,
    user: "Alice",
    message: "Yes, I use it for most of my projects. It's really powerful!",
    img: "",
    replyId: 8,
    date: "2024-10-12",
    time: "16:40", 
  },
  {
    id: 10,
    user: "Bob",
    message: "Yes, I use it for most of my projects. It's really powerful!",
    img: "/chat2.jpg",
    replyId: null,
    date: "2024-10-12",
    time: "16:45", 
  },
];
